// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `cosmos/auth/v1beta1/auth.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

#[derive(PartialEq,Clone,Default)]
pub struct BaseAccount {
    // message fields
    pub address: ::std::string::String,
    pub pub_key: ::protobuf::SingularPtrField<::protobuf::well_known_types::Any>,
    pub account_number: u64,
    pub sequence: u64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a BaseAccount {
    fn default() -> &'a BaseAccount {
        <BaseAccount as ::protobuf::Message>::default_instance()
    }
}

impl BaseAccount {
    pub fn new() -> BaseAccount {
        ::std::default::Default::default()
    }

    // string address = 1;


    pub fn get_address(&self) -> &str {
        &self.address
    }
    pub fn clear_address(&mut self) {
        self.address.clear();
    }

    // Param is passed by value, moved
    pub fn set_address(&mut self, v: ::std::string::String) {
        self.address = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_address(&mut self) -> &mut ::std::string::String {
        &mut self.address
    }

    // Take field
    pub fn take_address(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.address, ::std::string::String::new())
    }

    // .google.protobuf.Any pub_key = 2;


    pub fn get_pub_key(&self) -> &::protobuf::well_known_types::Any {
        self.pub_key.as_ref().unwrap_or_else(|| <::protobuf::well_known_types::Any as ::protobuf::Message>::default_instance())
    }
    pub fn clear_pub_key(&mut self) {
        self.pub_key.clear();
    }

    pub fn has_pub_key(&self) -> bool {
        self.pub_key.is_some()
    }

    // Param is passed by value, moved
    pub fn set_pub_key(&mut self, v: ::protobuf::well_known_types::Any) {
        self.pub_key = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_pub_key(&mut self) -> &mut ::protobuf::well_known_types::Any {
        if self.pub_key.is_none() {
            self.pub_key.set_default();
        }
        self.pub_key.as_mut().unwrap()
    }

    // Take field
    pub fn take_pub_key(&mut self) -> ::protobuf::well_known_types::Any {
        self.pub_key.take().unwrap_or_else(|| ::protobuf::well_known_types::Any::new())
    }

    // uint64 account_number = 3;


    pub fn get_account_number(&self) -> u64 {
        self.account_number
    }
    pub fn clear_account_number(&mut self) {
        self.account_number = 0;
    }

    // Param is passed by value, moved
    pub fn set_account_number(&mut self, v: u64) {
        self.account_number = v;
    }

    // uint64 sequence = 4;


    pub fn get_sequence(&self) -> u64 {
        self.sequence
    }
    pub fn clear_sequence(&mut self) {
        self.sequence = 0;
    }

    // Param is passed by value, moved
    pub fn set_sequence(&mut self, v: u64) {
        self.sequence = v;
    }
}

impl ::protobuf::Message for BaseAccount {
    fn is_initialized(&self) -> bool {
        for v in &self.pub_key {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.address)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.pub_key)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.account_number = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.sequence = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.address.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.address);
        }
        if let Some(ref v) = self.pub_key.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if self.account_number != 0 {
            my_size += ::protobuf::rt::value_size(3, self.account_number, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.sequence != 0 {
            my_size += ::protobuf::rt::value_size(4, self.sequence, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.address.is_empty() {
            os.write_string(1, &self.address)?;
        }
        if let Some(ref v) = self.pub_key.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if self.account_number != 0 {
            os.write_uint64(3, self.account_number)?;
        }
        if self.sequence != 0 {
            os.write_uint64(4, self.sequence)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> BaseAccount {
        BaseAccount::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "address",
                |m: &BaseAccount| { &m.address },
                |m: &mut BaseAccount| { &mut m.address },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<::protobuf::well_known_types::Any>>(
                "pub_key",
                |m: &BaseAccount| { &m.pub_key },
                |m: &mut BaseAccount| { &mut m.pub_key },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                "account_number",
                |m: &BaseAccount| { &m.account_number },
                |m: &mut BaseAccount| { &mut m.account_number },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                "sequence",
                |m: &BaseAccount| { &m.sequence },
                |m: &mut BaseAccount| { &mut m.sequence },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<BaseAccount>(
                "BaseAccount",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static BaseAccount {
        static instance: ::protobuf::rt::LazyV2<BaseAccount> = ::protobuf::rt::LazyV2::INIT;
        instance.get(BaseAccount::new)
    }
}

impl ::protobuf::Clear for BaseAccount {
    fn clear(&mut self) {
        self.address.clear();
        self.pub_key.clear();
        self.account_number = 0;
        self.sequence = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for BaseAccount {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for BaseAccount {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1ecosmos/auth/v1beta1/auth.proto\x12\x13cosmos.auth.v1beta1\x1a\x19c\
    osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a\x19google/proto\
    buf/any.proto\"\xfd\x01\n\x0bBaseAccount\x12\x18\n\x07address\x18\x01\
    \x20\x01(\tR\x07address\x12\\\n\x07pub_key\x18\x02\x20\x01(\x0b2\x14.goo\
    gle.protobuf.AnyR\x06pubKeyB-\xf2\xde\x1f\x11yaml:\"public_key\"\xea\xde\
    \x1f\x14public_key,omitempty\x12@\n\x0eaccount_number\x18\x03\x20\x01(\
    \x04R\raccountNumberB\x19\xf2\xde\x1f\x15yaml:\"account_number\"\x12\x1a\
    \n\x08sequence\x18\x04\x20\x01(\x04R\x08sequence:\x18\xd2\xb4-\x08Accoun\
    tI\xe8\xa0\x1f\0\x88\xa0\x1f\0\x98\xa0\x1f\0B+Z)github.com/cosmos/cosmos\
    -sdk/x/auth/typesJ\xbe\x06\n\x06\x12\x04\x03\0\x1c\x01\np\n\x01\x0c\x12\
    \x03\x03\0\x122f\x20Forked\x20from:\n\x20https://github.com/cosmos/cosmo\
    s-sdk/blob/v0.44.5/proto/cosmos/auth/v1beta1/auth.proto\n\n\x08\n\x01\
    \x02\x12\x03\x04\0\x1c\n\t\n\x02\x03\0\x12\x03\x06\0#\n\t\n\x02\x03\x01\
    \x12\x03\x07\0\x1e\n\t\n\x02\x03\x02\x12\x03\x08\0#\n\x08\n\x01\x08\x12\
    \x03\n\0@\n\t\n\x02\x08\x0b\x12\x03\n\0@\n\xdc\x01\n\x02\x04\0\x12\x04\
    \x0f\0\x1c\x01\x1a\xcf\x01\x20BaseAccount\x20defines\x20a\x20base\x20acc\
    ount\x20type.\x20It\x20contains\x20all\x20the\x20necessary\x20fields\n\
    \x20for\x20basic\x20account\x20functionality.\x20Any\x20custom\x20accoun\
    t\x20type\x20should\x20extend\x20this\n\x20type\x20for\x20additional\x20\
    functionality\x20(e.g.\x20vesting).\n\n\n\n\x03\x04\0\x01\x12\x03\x0f\
    \x08\x13\n\n\n\x03\x04\0\x07\x12\x03\x10\x02.\n\r\n\x06\x04\0\x07\x81\
    \xf4\x03\x12\x03\x10\x02.\n\n\n\x03\x04\0\x07\x12\x03\x11\x02.\n\r\n\x06\
    \x04\0\x07\x83\xf4\x03\x12\x03\x11\x02.\n\n\n\x03\x04\0\x07\x12\x03\x12\
    \x02.\n\r\n\x06\x04\0\x07\x8d\xf4\x03\x12\x03\x12\x02.\n\n\n\x03\x04\0\
    \x07\x12\x03\x14\x02:\n\r\n\x06\x04\0\x07\xca\xd6\x05\x12\x03\x14\x02:\n\
    \x0b\n\x04\x04\0\x02\0\x12\x03\x16\x02)\n\x0c\n\x05\x04\0\x02\0\x05\x12\
    \x03\x16\x02\x08\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x16\x16\x1d\n\x0c\n\
    \x05\x04\0\x02\0\x03\x12\x03\x16'(\n\x0c\n\x04\x04\0\x02\x01\x12\x04\x17\
    \x02\x19\x04\n\x0c\n\x05\x04\0\x02\x01\x06\x12\x03\x17\x02\x15\n\x0c\n\
    \x05\x04\0\x02\x01\x01\x12\x03\x17\x16\x1d\n\x0c\n\x05\x04\0\x02\x01\x03\
    \x12\x03\x17'(\n\r\n\x05\x04\0\x02\x01\x08\x12\x04\x17)\x19\x03\n\x0f\n\
    \x08\x04\0\x02\x01\x08\xed\xfb\x03\x12\x03\x18\x040\n\x0f\n\x08\x04\0\
    \x02\x01\x08\xee\xfb\x03\x12\x03\x182^\n\x0b\n\x04\x04\0\x02\x02\x12\x03\
    \x1a\x02\\\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x1a\x02\x08\n\x0c\n\x05\
    \x04\0\x02\x02\x01\x12\x03\x1a\x16$\n\x0c\n\x05\x04\0\x02\x02\x03\x12\
    \x03\x1a'(\n\x0c\n\x05\x04\0\x02\x02\x08\x12\x03\x1a)[\n\x0f\n\x08\x04\0\
    \x02\x02\x08\xee\xfb\x03\x12\x03\x1a*Z\n\x0b\n\x04\x04\0\x02\x03\x12\x03\
    \x1b\x02)\n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03\x1b\x02\x08\n\x0c\n\x05\
    \x04\0\x02\x03\x01\x12\x03\x1b\x16\x1e\n\x0c\n\x05\x04\0\x02\x03\x03\x12\
    \x03\x1b'(b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
